"""init

Revision ID: 393f85faa1a0
Revises: 
Create Date: 2023-02-28 11:27:00.214864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '393f85faa1a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
