"""tables for join test

Revision ID: 70bbb0716c7c
Revises: a43e5b9847a7
Create Date: 2023-02-17 15:57:13.691882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70bbb0716c7c'
down_revision = 'a43e5b9847a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('council',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__council'))
    )
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__permission'))
    )
    op.create_table('user_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('council_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['council_id'], ['council.id'], name=op.f('fk__user_permission__council_id__council')),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], name=op.f('fk__user_permission__permission_id__permission')),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk__user_permission__user_id__user_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__user_permission'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_permission')
    op.drop_table('permission')
    op.drop_table('council')
    # ### end Alembic commands ###
