"""init

Revision ID: 93837ccd633f
Revises: 
Create Date: 2023-02-28 14:50:42.517973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93837ccd633f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('council',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__council'))
    )
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__permission'))
    )
    op.create_table('user_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('f_name', sa.String(length=20), nullable=False),
    sa.Column('s_name', sa.String(length=20), nullable=False),
    sa.Column('l_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__user_account'))
    )
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email_address', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk__address__user_id__user_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__address'))
    )
    op.create_table('user_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('council_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['council_id'], ['council.id'], name=op.f('fk__user_permission__council_id__council')),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], name=op.f('fk__user_permission__permission_id__permission')),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk__user_permission__user_id__user_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__user_permission'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_permission')
    op.drop_table('address')
    op.drop_table('user_account')
    op.drop_table('permission')
    op.drop_table('council')
    # ### end Alembic commands ###
