"""initial

Revision ID: a43e5b9847a7
Revises: 
Create Date: 2023-02-17 13:14:53.046487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a43e5b9847a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('f_name', sa.String(length=20), nullable=False),
    sa.Column('s_name', sa.String(length=20), nullable=False),
    sa.Column('l_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__user_account'))
    )
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email_address', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk__address__user_id__user_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__address'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address')
    op.drop_table('user_account')
    # ### end Alembic commands ###
